# Generated by Django 5.2.6 on 2025-09-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
