apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
      version: blue
  template:
    metadata:
      labels:
        app: django
        version: blue
    spec:
      containers:
        - name: django
          image: your-django-image-blue
          ports:
            - containerPort: 8000
          env:
            # Example environment variables (adjust as needed)
            - name: DJANGO_SETTINGS_MODULE
              value: your_project.settings
            - name: DATABASE_URL
              value: postgres://user:password@db-host:5432/dbname
          readinessProbe:
            httpGet:
              path: /healthz/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20



