#!/bin/bash

echo "Applying blue deployment..."
kubectl apply -f blue_deployment.yaml

echo "Applying green deployment..."
kubectl apply -f green_deployment.yaml

echo "Applying service..."
kubectl apply -f kubeservice.yaml

echo "Waiting for green pods to start..."
sleep 5

echo "Checking logs of green deployment:"
GREEN_POD=$(kubectl get pods -l app=django,version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs "$GREEN_POD"

